#Models were generated by loading a structure formatted color table, that was saved as ModelList.mrml.

./ontology_hierarchy_creator.pl -o DataLibrariesMouse/half_25UM/ModelHierarchy.mrml -m DataLibrariesMouse/half_25UM/ModelList.mrml -h DataLibrariesMouse/half_25UM/civm_mouse_v2_ontology.csv -c DataLibrariesMouse/half_25UM/N51667_labels_Structure_lookup.txt -t Name
./mrml_key_strip.pl DataLibrariesMouse/half_25UM/ModelHierarchy.mrml
